language: c++
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcppunit-dev
  - sudo apt-get install -qq libnuma-dev
  - chmod +x getLibJitBuilder.sh
  - ./getLibJitBuilder.sh

compiler:
  - gcc

env:
  - USE_TAGGING=true   GC_TYPE=generational
  - USE_TAGGING=true   GC_TYPE=mark_sweep
  - USE_TAGGING=true   GC_TYPE=copying
  - USE_TAGGING=true   GC_TYPE=omr_gc
  - USE_TAGGING=true   GC_TYPE=omr_gc       CACHE_INTEGER=false  DEFAULT_OMR_JIT_ON=true
  
  - USE_TAGGING=false  GC_TYPE=generational CACHE_INTEGER=true
  - USE_TAGGING=false  GC_TYPE=mark_sweep   CACHE_INTEGER=true
  - USE_TAGGING=false  GC_TYPE=copying      CACHE_INTEGER=true
  - USE_TAGGING=false  GC_TYPE=omr_gc       CACHE_INTEGER=true
  
  - USE_TAGGING=false  GC_TYPE=generational CACHE_INTEGER=false
  - USE_TAGGING=false  GC_TYPE=mark_sweep   CACHE_INTEGER=false
  - USE_TAGGING=false  GC_TYPE=copying      CACHE_INTEGER=false
  - USE_TAGGING=false  GC_TYPE=omr_gc       CACHE_INTEGER=false

script:
    - make test
    - make bench
    - make clean
    - make unittests
